#!/usr/bin/env ruby

require "minitest/autorun"
require "minitest/pride"
load "convert"

define Equations do

	before do
		@equations = Equations.new
	end

	define "hz_to_m" do
		it "must return correct value" do

		end
	end

	define "m_to_hz" do
		it "must return correct value" do
			
		end
	end

end